#ifndef DECOMREN_CONFIG_H_INCLUDED
#define DECOMREN_CONFIG_H_INCLUDED

#define MAX_ALPHA 0.99999f
#define MIN_ALPHA 0.00001f
#define EARLY_STOP_T 0.0001f
#define STEP_SZ_SCALE 100.f

#define MAX_NUM_SAMPLE 3
#define BLOCK2D_X 16
#define BLOCK2D_Y 16
#define MAX_OCTREE_LEVELS 16

// Below are the derived term from above
#define BLOCK2D_N (BLOCK2D_X * BLOCK2D_Y)
#define NBITS_DIRECTIONAL_MORTON_CODE (3 * MAX_OCTREE_LEVELS)

#endif
